# Generated by Django 4.1 on 2023-01-06 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=27)),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(15)])),
                ('residence', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
