# Generated by Django 4.1 on 2023-01-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_member_delete_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='year',
        ),
        migrations.AddField(
            model_name='member',
            name='studyyear',
            field=models.IntegerField(default=2, max_length=1),
        ),
    ]
