# Generated by Django 4.1 on 2023-01-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_studyyear_member_study_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='study_year',
            field=models.IntegerField(default=2),
        ),
    ]
